FROM ubuntu:21.04

ENV PHP_VERSION=php7.4 \
COMPOSER_VERSION=2.2.0 \
LANG=es_ES.UTF-8 \
LANGUAGE=es_ES.UTF-8 \
LC_COLLATE=C \
LC_CTYPE=es_ES.UTF-8 \
DEBIAN_FRONTEND=noninteractive


LABEL autor="Martin Vilche <mfvilche@gmail.com>" \
      io.k8s.description="php s2i images" \
      io.k8s.display-name="php Applications" \
      io.openshift.tags="builder,php,composer,centos" \
      io.openshift.expose-services="8080" \
      io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"
      

RUN apt update && apt --no-install-recommends install apt-utils locales -y && apt upgrade -y && \
locale-gen $LANG && localedef -i es_ES -f UTF-8 $LANG && \
dpkg-reconfigure locales
RUN echo "LANG=$LANG" > /etc/locale.conf && \
apt --no-install-recommends install nodejs git $PHP_VERSION openssl unzip curl netcat apache2 \
$PHP_VERSION-common $PHP_VERSION-mysql $PHP_VERSION-xml $PHP_VERSION-xmlrpc $PHP_VERSION-curl $PHP_VERSION-gd $PHP_VERSION-imagick $PHP_VERSION-cli \ 
$PHP_VERSION-dev $PHP_VERSION-imap $PHP_VERSION-mbstring $PHP_VERSION-opcache $PHP_VERSION-soap $PHP_VERSION-zip $PHP_VERSION-intl ca-certificates -y

RUN echo "Listen 8080" > /etc/apache2/ports.conf && \
sed -ri -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' /etc/apache2/apache2.conf && \
sed -i -e "s/^short_open_tag = Off/short_open_tag = On/" /etc/php/7.4/apache2/php.ini && \
sed -i -e "s/^post_max_size = 8M/post_max_size = 80M/" /etc/php/7.4/apache2/php.ini && \
sed -i -e "s/^upload_max_filesize = 2M/upload_max_filesize = 40M/"  /etc/php/7.4/apache2/php.ini && \
sed -i -e "s/^LogLevel warn/LogLevel Error/" /etc/php/7.4/apache2/php.ini && \
sed -i "/;session.save_path/c\session.save_path=\/tmp" /etc/php/7.4/apache2/php.ini && \
sed -i -e "s/^;curl.cainfo =/curl.cainfo='\/etc\/php\/7.4\/apache2\/cacert.pem'/" /etc/php/7.4/apache2/php.ini && \
sed -i -e "s/^;openssl.cafile=/openssl.cafile='\/etc\/php\/7.4\/apache2\/cacert.pem'/" /etc/php/7.4/apache2/php.ini && \
curl -o /etc/php/7.4/apache2/cacert.pem https://curl.se/ca/cacert.pem && \
a2enmod rewrite


RUN echo "VERSION PHP INSTALADA: " && php -version && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=$COMPOSER_VERSION && rm composer-setup.php && \
apt autoremove -y && apt clean && rm -rf /var/lib/apt/lists/*

COPY s2i/bin/ /usr/libexec/s2i

#COPY security.conf /etc/apache2/conf-enabled/security.conf

RUN mkdir /opt/composer_env && usermod -u 1001 www-data && usermod -aG 0 www-data && rm -rf /etc/localtime /var/www/html/* && touch /etc/localtime /etc/timezone && \
mkdir -p /usr/share/composer_install && \
chown  -R 1001 /opt/composer_env /var/log/apache2/ /run/apache2 /var/www/html /usr/share/apache2 /etc/apache2 /etc/timezone /etc/localtime /usr/libexec/s2i && \
chgrp -R 0 /opt/composer_env /var/log/apache2/ /run/apache2 /var/www/html /usr/share/apache2 /etc/apache2 /etc/timezone /etc/localtime /usr/libexec/s2i && \
chmod -R g=u /opt/composer_env /var/log/apache2/ /run/apache2  /var/www/html /etc/apache2 /usr/share/apache2 /etc/timezone /etc/localtime /usr/libexec/s2i && \
chmod +x /usr/libexec/s2i/*

WORKDIR /var/www/html

ENV HOME=/usr/share/apache2 \
APACHE_CONFIGDIR=/etc/apache2 

USER 1001:0

EXPOSE 8080

CMD ["/usr/libexec/s2i/run"]
